"""Make success column non-nullable in reminder_logs

Revision ID: 584b1942c79f
Revises: 8cd9abbfbee6
Create Date: 2025-11-11 13:59:22.893139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '584b1942c79f'
down_revision = '8cd9abbfbee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_logs', schema=None) as batch_op:
        batch_op.alter_column('success',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_logs', schema=None) as batch_op:
        batch_op.alter_column('success',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###
