"""Add unique constraint on user_id and name in subscriptions

Revision ID: 58517583768d
Revises: 210d6038ec97
Create Date: 2025-11-05 18:58:29.217446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58517583768d'
down_revision = '210d6038ec97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_subscription_name', ['user_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_subscription_name', type_='unique')

    # ### end Alembic commands ###
