"""Replace billing_cycle String with Enum

Revision ID: 8cd9abbfbee6
Revises: 58517583768d
Create Date: 2025-11-06 21:08:06.463552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cd9abbfbee6'
down_revision = '58517583768d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('billing_cycle',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('weekly', 'monthly', 'yearly', name='billingcycleenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('billing_cycle',
               existing_type=sa.Enum('weekly', 'monthly', 'yearly', name='billingcycleenum'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
